---
- name: Deploy Next.js Application
  hosts: nextjs_servers
  become: yes
  vars:
    node_version: "18"
    app_dir: "/home/ec2-user/todo-application"
    repo_dir: "{{ playbook_dir }}/../todo-application"

  tasks:
    - name: Update yum cache
      yum:
        update_cache: yes

    - name: Install EPEL repository
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        state: present
      when: ansible_distribution == 'Amazon'

    - name: Install required packages
      yum:
        name:
          - curl
          - git
          - rsync
        state: present

    - name: Download Node.js setup script
      get_url:
        url: https://rpm.nodesource.com/setup_{{ node_version }}.x
        dest: /tmp/setup_node.sh
        mode: '0755'

    - name: Execute Node.js setup script
      command: /tmp/setup_node.sh
      args:
        creates: /etc/yum.repos.d/nodesource.repo

    - name: Install Node.js
      yum:
        name: nodejs
        state: present

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes
        state: present

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ec2-user
        group: ec2-user

    - name: Copy Next.js application files
      synchronize:
        src: "{{ repo_dir }}/"
        dest: "{{ app_dir }}"
        rsync_opts:
          - "--exclude=node_modules"
          - "--exclude=.git"
          - "--exclude=.next"
      become: no

    - name: Install npm dependencies
      npm:
        path: "{{ app_dir }}"
      become: no

    - name: Build Next.js application
      command:
        chdir: "{{ app_dir }}"
        cmd: npm run build
      become: no

    - name: Start/Restart Next.js application with PM2
      command:
        chdir: "{{ app_dir }}"
        cmd: "pm2 start npm --name 'todo-application' -- start || pm2 restart todo-application"
      become: no

    - name: Save PM2 process list
      command: pm2 save
      become: no

    - name: Setup PM2 startup script
      command: pm2 startup
      become: yes